personalsite/article/urls.py
from django.urls import path
from . import views

# 部署应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detial/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

personalsite/personalsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

personalsite/userprofile/urls.py
# -*- coding:utf-8 -*-

from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

personalsite/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    created = models.DateTimeField(default=timezone.now)
    # auto_now=True 指定每次数据更新写入时间
    updated = models.DateTimeField(auto_now=True)

    # Meta提供元数据, 元数据表示任何不是字段的东西。
    # 比如排序(ordering), 单复数(verbose_name, verbose_name_plural), 数据库表名(db_table)
    # ordering = ('-created') -> created 按创建时间 - 倒序 
    # 在网站首页展示, 最新文章呈现在最上面
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

personalsite/userprofile/models.py
from django.db import models

# Create your models here.

personalsite/article/forms.py
from django import forms
from .models import ArticlePost


# forms.ModelForm适用于与数据库交互, 比如新建、更新字段
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指定数据模型来源
        model = ArticlePost
        # 定义表单包含字段, created、updated字段自动生成, author默认指定为id=1的用户
        fields = ('title', 'body')

personalsite/userprofile/forms.py
# -*- coding:utf-8 -*-
from django import forms


# forms.Form适用于不与数据库交互
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 继承forms.ModelForm, 在Meta辅助类中, 从模型创建Form类, 表单会生成已有字段
class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2')
            return data.get('password')
        else:
            return forms.ValidationError('两次密码输入不一致, 请重试!')

personalsite/article/views.py
import markdown
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
from .forms import ArticlePostForm
from django.contrib.auth.models import User

# Create your views here.

def article_list(request):
    articles = ArticlePost.objects.all()
    context = {'articles': articles}
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    article.body = markdown.markdown(article.body,
        extensions=[
        # 语法、表格等常用扩展
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
    ])
    context = {'article': article}
    return render(request, 'article/detail.html', context)


def article_create(request):
    if 'POST' == request.method:
        article_post_form = ArticleForm(data=request.POST)
        # 提交数据满足ArticleForm模型要求
        if article_post_form.is_valid():
            # 保存数据暂时不提交数据库
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=1)
            # 文章保存到数据库
            new_article.save()
            return redirect('article:article_list')
        else:
            return HttpResponse('表单内容有误, 请重新输入')
    else:
        article_post_form = ArticleForm()
        context = {'article_post_form': article_post_form}
        return render(request, 'article/create.html', context)


def article_safe_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect('article:article_list')


def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if 'POST' == request.method:
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect('article:article_detail', id=id)
        else:
            return HttpResponse("表单内容有误, 请重新填写!")
    else:
        article_post_form = ArticlePostForm()
        context = {'article': article, 'article_post_form': article_post_form}
        return render(request, 'article/update.html', context)

personalsite/userprofile/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def user_login(request):
    if 'POST' == request.method:
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data清洗数据
            data = user_login_form.cleaned_data
            # 账户和密码匹配数据库中某一用户数据
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 保存数据到session
                login(request, user)
                return redirect('article:article_list')
            else:
                return HttpResponse('账户和密码输入有误, 请重新输入')
        else:
            return HttpResponse('账户和密码输入不合法')
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse('请使用GET或者POST方法请求数据')


def user_logout(request):
    logout(request)
    return redirect('article:article_list')

personalsite/templates/article/create.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block title %}
    写文章
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">文章内容</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

personalsite/templates/article/detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    文章详情
{% endblock %}

{% block content %}
<div class='container'>
    <div class='row'>
        <h1 class='col-12 mt-4 mb-4'>{{ article.title }}</h1>
        <div class='col-12 alert alert-success'>作者: {{ article.author }}
            <a href='#' onclick="confirm_safe_delete()" style='color:red;'>删除文章</a>
            <a href='{% url "article:article_update" article.id %}'>编辑文章</a>
            <form style="display:none;"
                  id="safe_delete"
                  action='{% url "article:article_safe_delete" article.id %}'
                  method='POST'
            >
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
        </div>
        <div class='col-12'>
            <p>{{ article.body|safe }}</p>
        </div>
    </div>
</div>
<script>
    function confirm_safe_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: '确认删除',
            // 正文
            content: '确认删除这篇文章',
            // 点击确认按钮后调用的回调函数
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            },
        })
    }
</script>
{% endblock %}

personalsite/templates/article/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    文章列表页
{% endblock %}

{% block content %}
<div class='container'>
    <div class='row mt-2'>
    {% for article in articles %}
        <div class='col-4 mb-4'>
            <div class='card h-100'>
                <h4 class='card-header'>{{ article.title }}</h4>
                <div class='card-header'>
                    <p class='card-text'>{{ article.body|slice:'100' }}...</p>
                </div>
                <div class='card-footer'>
                    <a href="{% url 'article:article_detail' article.id %}" class='btn btn-primary'>阅读本文</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

personalsite/templates/article/update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    更新文章
{% endblock title %}

{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-12'>
            <form method='POST' action='.'>
                {% csrf_token %}
                <div class='form-group'>
                    <label for='title'>文章标题</label>
                    <input type='text' class='form-control' id='title' name='title' value='{{ article.title }}'>
                </div>
                <div class='form-group'>
                    <label for='body'>文章内容</label>
                    <textarea type='text' class='form-control' id='body' name='body' row='12'>{{ article.body }}</textarea>
                </div>
                <button type='submit' class='btn btn-primary'>提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

personalsite/templates/base.html
{% load staticfiles %}

<html>
<head>
    <meta charset="utf-8">     
    <title>{% block title %}{% endblock %}</title>
    <link rel='stylesheet' href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel='stylesheet' href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    {% include 'header.html' %}
    {% block content %}{% endblock %}
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.5.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- layer依赖jquery -->
    <script src="{% static 'layer/layer.js' %}"></script>
</body>
</html>

personalsite/templates/footer.html
<footer class='py-3 bg-dark fixed-bottom'>
    <div class='container'>
        <p class='m-0 text-center text-white'>Copyright &copy;www.kameng.com 2020</p>
    </div>
</footer>

personalsite/templates/header.html
<nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
    <div class='container'>
        <a class='navbar-brand' href='#'>我的网站</a>
        <div>
            <ul class='navbar-nav'>
                <li class='nav-item'>
                    <a class='nav-link' href='{% url "article:article_list" %}'>文章</a>
                </li>
                <li class='nav-item'>
                    <a class='nav-link' href='{% url "article:article_create" %}'>写文章</a>
                </li>
                {% if user.is_authenticated %}
                <li class='nav-item dropdown'>
                    <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>{{ user.username }}</a>
                    <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
                        <a class='dropdown-item' href='{% url "userprofile:logout" %}'>退出登录</a>
                    </div>
                </li>
                {% else %}
                <li class='nav-item'>
                    <a class='nav-link' href='{% url "userprofile:login" %}'>登录</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

personalsite/templates/userprofile/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}登录{% endblock title %}

{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-12'>
            <form method='post' action='.'>
                {% csrf_token %}
                <div class='form-group'>
                    <label for='username'>账号</label>
                    <input type='text' class='form-control' id='username' name='username'>
                </div>
                <div class='form-group'>
                    <label for='password'>密码</label>
                    <input type='password' class='form-control' id='password' name='password'>
                </div>
                <button type='submit' class='btn btn-primary'>登录</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}